document.addEventListener('DOMContentLoaded', function () {
    const caseStudies = [
        {
            title: "Case Study 1 - Suno",
            description: "Suno, an AI start-up, generates music by claiming to create entirely new outputs. However, it has faced major controversy over copyright infringement. Major music labels, including Sony, Universal, and Warner, sued Suno for allegedly using copyrighted music to train their AI, leading to outputs that closely mimic existing works. Suno did not deny using copyrighted material but claimed that its training data is confidential. This lawsuit is the first of its kind against an AI music generator, raising significant legal questions. Additionally, Suno faced ethical backlash when its AI-generated song ‘Soul of the Machine’ was criticized for cultural appropriation, using African-American blues style without acknowledging its historical significance. Critics argue that AI like Suno’s could undermine human creativity and the authenticity of music. The case may lead to changes in business models and stricter copyright laws for AI-generated content.",
            image: "images/suno.png"
        },
        {
            title: "Case Study 2 - Udio",
            description: "Udio is another AI music generation start-up that has gained attention, notably through the viral parody ‘BBL Drizzy’ - a diss track beat by Metro Boomin that went viral due to its connection to the Drake–Kendrick Lamar feud. The track, which samples an AI-generated song by comedian King Willonius, became the first notable example of AI sampling in mainstream hip-hop, amassing over 3.3 million streams on SoundCloud in just a week. This highlighted the increasing influence and controversy surrounding AI in music production, further complicating the landscape of intellectual property rights. Udio has faced legal issues over copyright infringement, with major music labels suing the company for creating tracks resembling existing works like Mariah Carey’s ‘All I Want for Christmas Is You.’ The lawsuit claims Udio used music without proper authorization, and the company has been criticized for its lack of transparency in handling the allegations. The RIAA’s chairman also condemned Udio for exploiting artists' work without proper compensation, highlighting ongoing tensions between AI music and intellectual property rights.",
            image: "images/udio.jpg",
            audio: "audio/bbl-drizzy-new-new.mp4"
        },
        {
            title: "Case Study 3 - Lyria",
            description: "Lyria is Google's AI music generation model, capable of producing lyrics, vocals, and instrumentals. The tool has sparked significant ethical and legal concerns due to its use of copyrighted music for training without obtaining prior permission from rights holders. Google employed an ‘ask for forgiveness, not permission’ strategy, revealing the model to rights-holders after training, which critics argue undermines fair negotiation. This approach has led to challenges in negotiations with major music labels, who were confronted with the unauthorized use of their content. Google’s stance that generative AI training falls under 'fair use' is contentious, raising doubts about its commitment to ethical practices. This represents a shift from Google's earlier projects, like Magenta, which used only authorized or public domain music data. The controversy around Lyria highlights the need for clearer guidelines on the use of copyrighted material in AI training.",
            image: "images/lyria.png"
        },
        {
            title: "Case Study 4 - Claude",
            description: "Claude is an AI chatbot developed by Anthropic that has been involved in legal and ethical controversies, particularly around copyright infringement. Universal Music Publishing Group, Concord Music Group, and ABKCO filed a lawsuit against Claude for allegedly copying and distributing copyrighted lyrics without permission. The plaintiffs claim that Claude generates lyrics that directly resemble portions of copyrighted songs, even when specific artists or songs are not mentioned in the prompts. Anthropic defends its actions by arguing that using copyrighted content for training is ‘fair use,’ given the vast data required to develop complex AI models. They assert that their safeguards prevent the output of copyrighted material, making further legal action unnecessary. This case underscores the ongoing debate over the limits of 'fair use' in AI training and the legal responsibilities of AI developers.",
            image: "images/claude.png"
        },
        {
            title: "Case Study 5 - FN Meka",
            description: "FN Meka is a virtual rapper created through AI, designed to reflect modern music trends. The character’s music, generated by algorithms, raises questions about authenticity, especially in genres like hip-hop, which are deeply rooted in cultural and historical experiences. Critics argue that FN Meka's AI-driven persona risks devaluing the authenticity of the art form and engages in cultural appropriation by mimicking aspects of marginalized cultures. The controversy also extends to the ownership and copyright of AI-generated music, as it’s unclear who holds the rights—whether it’s the developers, the owning company, or if it falls outside current copyright laws due to the lack of direct human authorship. FN Meka’s existence challenges the music industry to establish ethical guidelines that respect cultural heritage and artistic integrity. The mixed reception of FN Meka highlights the ongoing debate about AI’s role in the creative arts, whether as a tool to enhance human creativity or as a potential competitor to human talent.",
            image: "images/fnmeka.jpeg"
        }
    ];

    let currentCase = 0;

    function showCaseStudy(index) {
        const caseStudy = caseStudies[index];
        if (!caseStudy) return;

        // Update the title, description, and image
        document.getElementById("caseStudyTitle").innerText = caseStudy.title;
        document.getElementById("caseStudyDescription").innerText = caseStudy.description;
        document.getElementById("caseStudyImage").src = caseStudy.image;

        // Clear previous audio controls if they exist
        const caseStudyDescription = document.getElementById("caseStudyDescription");
        const existingAudioControls = document.getElementById("caseStudyAudioControls");
        if (existingAudioControls) {
            existingAudioControls.remove();
        }

        // append the audio controls
        if (caseStudy.audio) {
            const audioControls = document.createElement('div');
            audioControls.id = "caseStudyAudioControls";
            audioControls.style.display = "flex";
            audioControls.style.alignItems = "center"; // Ensure icon and text alignment
            audioControls.style.marginTop = "15px";

            // play button with the toggle switch
            audioControls.innerHTML = `
                <div class="toggle-cont">
                  <input class="toggle-input" id="toggle${index}" name="toggle" type="checkbox" onchange="togglePlayAudio(${index})" />
                  <label class="toggle-label" for="toggle${index}">
                    <div class="cont-label-play">
                      <span class="label-play"></span>
                    </div>
                  </label>
                </div>
                <audio id="caseStudyAudio${index}">
                    <source src="${caseStudy.audio}" type="audio/mpeg">
                    Your browser does not support the audio element.
                </audio>
                <span class="play-audio-text">Click to listen to 'BBL Drizzy,' an AI-generated song that was later sampled by Metro Boomin.</span>
            `;
            caseStudyDescription.appendChild(audioControls);
        }

        // Handle progress dots
        const dots = document.querySelectorAll(".dot");
        dots.forEach((dot, i) => {
            dot.className = dot.className.replace(" active", "");
            if (i === index) {
                dot.className += " active";
            }
        });
    }

    // Function to handle the toggle play/pause action
    window.togglePlayAudio = function(index) {
        const audio = document.getElementById(`caseStudyAudio${index}`);
        const toggleInput = document.getElementById(`toggle${index}`);

        if (toggleInput.checked) {
            audio.play();
        } else {
            audio.pause();
        }
    };

    function openPopup() {
        document.getElementById("caseStudiesPopup").style.display = "flex";
        showCaseStudy(currentCase);
    }

    function closePopup() {
        document.getElementById("caseStudiesPopup").style.display = "none";
    }

    function prevCaseStudy() {
        currentCase = (currentCase - 1 + caseStudies.length) % caseStudies.length;
        showCaseStudy(currentCase);
    }

    function nextCaseStudy() {
        currentCase = (currentCase + 1) % caseStudies.length;
        showCaseStudy(currentCase);
    }

    function currentCaseStudy(index) {
        currentCase = index - 1;
        showCaseStudy(currentCase);
    }

    // Attach event listener to the "View Case Studies" button
    const caseStudiesButton = document.querySelector('.case-studies .btn');
    if (caseStudiesButton) {
        caseStudiesButton.addEventListener('click', openPopup);
    } else {
        console.error('Case studies button not found');
    }

    // Attach event listener to the close button in the popup
    const closeButton = document.querySelector('.close-popup');
    if (closeButton) {
        closeButton.addEventListener('click', closePopup);
    } else {
        console.error('Close button in case studies popup not found');
    }

    // Attach event listeners for navigating case studies
    const leftArrow = document.querySelector('.left-arrow');
    if (leftArrow) {
        leftArrow.addEventListener('click', prevCaseStudy);
    } else {
        console.error('Left arrow button not found');
    }

    const rightArrow = document.querySelector('.right-arrow');
    if (rightArrow) {
        rightArrow.addEventListener('click', nextCaseStudy);
    } else {
        console.error('Right arrow button not found');
    }

    // LEGALITY POPUP CODE
    const learnMoreButton = document.querySelector('.small-btn');
    if (learnMoreButton) {
        learnMoreButton.addEventListener('click', openLegalPopup);
    } else {
        console.error('Learn More button not found');
    }

    function openLegalPopup() {
        document.getElementById("legalPopup").style.display = "flex";
    }

    function closeLegalPopup() {
        document.getElementById("legalPopup").style.display = "none";
    }

    const closeLegalButton = document.querySelector('.close-popup-legal');
    if (closeLegalButton) {
        closeLegalButton.addEventListener('click', closeLegalPopup);
    } else {
        console.error('Close button in legal popup not found');
    }

    // ETHICS POPUP CODE
    const ethicsLearnMoreButton = document.querySelector('#ethicsLearnMoreButton');
    if (ethicsLearnMoreButton) {
        ethicsLearnMoreButton.addEventListener('click', openEthicsPopup);
    } else {
        console.error('Learn More button on the ethics page not found');
    }

    function openEthicsPopup() {
        document.getElementById("ethicsPopup").style.display = "flex";
    }

    function closeEthicsPopup() {
        document.getElementById("ethicsPopup").style.display = "none";
    }

    const closeEthicsButton = document.querySelector('.close-popup-legal');
    if (closeEthicsButton) {
        closeEthicsButton.addEventListener('click', closeEthicsPopup);
    } else {
        console.error('Close button in ethics popup not found');
    }
});
